### PR TITLE
feat: home page added

### PR DESCRIPTION
**Pull request by Developers-codz**
Added home page
Page is fully responsive
search icon toggles and open search bar.
Added owl carousel

Do review and give your valuable feedbacks. thank you :)

### CODE REVIEW

**Comment by Developers-codz** [comment]
Screenshot (46)
Screenshot (49)
Screenshot (48)

**Review by arjun-computer-geek — APPROVED** [review]
looking good. And clean code

**Review by partha8 — APPROVED** [review]
Looks good, and I like the code for the slideshow, its a slideshow (carousel) right? UI looks amazing!

**Comment by Developers-codz** [comment]
> Looks good, and I like the code for the slideshow, its a slideshow (carousel) right? UI looks amazing!

thank you :) yep, its slideshow

**Pull request merged**
