### PR TITLE
feat: sign up page done

### PR DESCRIPTION
**Pull request by Developers-codz**
Created Signup Page
page link : https://deploy-preview-8--beadsandbeyonds.netlify.app/signup.html

Thank you for reviewing it :)

### CODE REVIEW

**Review by arjun-computer-geek — APPROVED** [review]
Looks good to me

**Review by Shailseen — APPROVED** [review]
add screenshots for easy to PR. otherwise all look good from me.

**Comment by Developers-codz** [comment]
> add screenshots for easy to PR. otherwise all look good from me.

I have provided the link to the page in first comment :)

**Review by yash9263 — APPROVED** [review]

**Comment by yash9263** [comment]
Looks good to me

**Pull request merged**
